Feat/rental
othniel-agera/book-rental-store pull request #4
Opened 2022-11-20 06:23 UTC by othniel-agera

2022-11-20 22:22 UTC, KufreOkon requested changes

2022-11-20 22:22 UTC, KufreOkon commented on controllers/rental.controller.js
> +    let localFilter = { ...filter };
I don't think this destructuring is necessary, you can use `filter` here as well, no need to create another variable.

2022-11-20 22:22 UTC, KufreOkon commented on controllers/rental.controller.js
> +      limit: limit || parseInt(limit, 10),
Since we now have Joi validator for `page` and `limit`, I think there is no need for the 'parseInt' casting. Also, supposing the validator is not effective and invalid page and limit values slip through, those invalid values will be sent to `advancedResults` except they contained empty space then `NaN` will be sent to `advancedResults` which I think is not the expected behaviour.
I would suggest passing page and limit as is.

2022-11-20 22:22 UTC, KufreOkon commented on controllers/rental.controller.js
> +
Implementing it this way is fine but you may find it difficult to paginate(which is very likely to be needed as more books get checkout by this user) accurately. So you can achieve the same result with one db query with pagination as well.

Try this
```javascript
const rentals = await advancedResults(Rental, { user: userId }, {
      page: req.query.page,
      distinct: 'book',
      populate: 'book',
      select:'book'
    });
```
Or
```javascript
const rentals = await advancedResults(Rental, { user: userId }, {
      page: req.query.page,
      distinct: 'book',
      populate: 'book',
      select:'book._id, book.title, etc'
    });
```
Then 
```javascript
const books = {...rentals, data:rentals.data.map(r => r.book)}
```

2022-11-21 13:30 UTC, othniel-agera commented on controllers/rental.controller.js
> +    let localFilter = { ...filter };
Please explain, if I don't do destructuring how would I get `page, limit, select & sort` and get the rest of filter?

2022-11-23 09:32 UTC, merged